### PR TITLE
Fix outdated verbiage on invitations

### PR DESCRIPTION
**Pull request by fluffy-critter**
Members are not able to generate invites, and are directed to ask their friend to fill out the form.

### CODE REVIEW

**Comment by aredridel** [comment]
You can in fact still have people request invites. Good for meetups and face to face.

**Comment by fluffy-critter** [comment]
How does one do that, then? The site verbiage is unclear on that point. How does one request an invite except by filling out the form?

**Comment by aredridel** [comment]
If you know a member, you ask them. Like direct face to face or 1:1 virtual interaction.

**Comment by fluffy-critter** [comment]
But then what does the member do?

**Comment by aredridel** [comment]
Fill out the form or `/admin`

**Comment by fluffy-critter** [comment]
Could you please join in on the conversation on `#meta`? Thanks.

**Pull request closed without merging**
